import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import 'react-time-picker/dist/TimePicker.css';
import 'react-clock/dist/Clock.css';

import SessionProviderWrapper from "@/lib/providers/SessionProviderWrapper";
import { Toaster } from "sonner";
import Nav from "@/components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProviderWrapper>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-flow-col grid-cols-[auto,1fr]`}
        >
          <Nav />
          <main>{children}</main>
          <Toaster richColors />
        </body>
      </html>
    </SessionProviderWrapper>
  );
}
