import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { prisma } from "@/lib/prisma";
import { authOptions } from "@/utils/authOptions";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
	title: "DashBoard ",
	description: "Generated by create next app",
};

export default async function DashBoardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	if (!session || !session!.user || !session!.user.email) {
		return {
			redirect: {
				destination: "/auth/signin",
				permanent: false,
			},
		};
	}

	const user = await prisma.users.findUnique({
		where: {
			email: session!.user!.email,
		},
	});

	if (!user || (user.role !== "ADMIN" && user.role !== "USER")) {
		return {
			redirect: {
				destination: "/auth/signin",
				permanent: false,
			},
		};
	}

	return (
		<nav>
			<h2>Dashboard</h2>
			{user.role === "ADMIN" ? <h2>Admin DashBoard</h2> : null}
			{user.role === "USER" || user.role === "ADMIN" ? <h2>User DashBoard</h2> : null}
			{children}
		</nav>
	);
}
